# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silabo', '0002_auto_20200410_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='clase',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
