# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_curso_asignar'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='seccion',
            field=models.IntegerField(blank=True, choices=[(0, 'Matutino'), (1, 'Vespertino')], default=0, null=True),
        ),
    ]
